changelog:
  exclude:
    authors:
      - dependabot
      - dependabot[bot]
    labels:
      - ignore-for-release
  categories:
    - title: Breaking Changes
      labels: [breaking, breaking-change]
    - title: Features
      labels: [feat, feature, enhancement]
    - title: Bug Fixes
      labels: [fix, bug]
    - title: Chores
      labels: [chore, documentation, dependencies]
    - title: Other Changes
      labels: ["*"]
