"""Static constants and text templates for Kensa."""

from __future__ import annotations

from pathlib import Path

DEFAULT_EVAL_PATHS = ("tests/evals",)
KENSA_DIR = Path(".kensa")
INSPECT_DIR = KENSA_DIR / "inspect"
KENSA_SETTINGS_SCHEMA_VERSION = "kensa.settings.v1"
KENSA_SETTINGS_PATH = KENSA_DIR / "settings.json"
SMOKE_CASE_ID = "kensa_smoke"
SMOKE_NODEID_FRAGMENT = "test_kensa_smoke.py::test_kensa_smoke"
TRACE_IMPORT_LATEST_SCHEMA_VERSION = "kensa.trace_import_latest.v1"
TRACE_IMPORTS_DIR = KENSA_DIR / "traces" / "imports"

ENDPOINT_ENV_KEY_FRAGMENTS = ("URL", "URI", "ENDPOINT", "HOST", "BASE")
LOCAL_ENDPOINT_HOSTS = {"localhost", "127.0.0.1", "::1", "0.0.0.0"}

SETUP_HANDOFF_PROMPT = (
    "Use the generated kensa-evals skill to continue the Kensa lifecycle for this repo: "
    "setup -> evidence -> inspect -> approval -> generate -> verify. Start with state detection. "
    "Read .kensa/settings.json for the selected trace source. Detect credentials by name only; "
    "never read or print API keys or .env files."
)

# fmt: off
CLI_LOGO = (
    "┌────────────────────────────────────────────────────────┐\n"
    "│ ░██    ░██ ░███████  ░████████   ░███████   ░██████    │\n"
    "│ ░██   ░██ ░██    ░██ ░██    ░██ ░██              ░██   │\n"
    "│ ░███████  ░█████████ ░██    ░██  ░███████   ░███████   │\n"
    "│ ░██   ░██ ░██        ░██    ░██        ░██ ░██   ░██   │\n"
    "│ ░██    ░██ ░███████  ░██    ░██  ░███████   ░█████░██  │\n"
    "└────────────────────────────────────────────────────────┘"
)
# fmt: on

CLI_EPILOG = """\b
Examples:
  kensa init
  kensa doctor --json
  kensa import --from jsonl --source traces.jsonl
  kensa traces sample --json
  kensa eval --workers 1
  kensa eval -- --maxfail=1 -q

Pass extra pytest arguments after --.
"""

WORKFLOW_TEXT = """name: Kensa

on:
  pull_request:
  push:
    branches: [main]

jobs:
  kensa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        if: ${{ hashFiles('uv.lock') == '' }}
        with:
          python-version: "3.11"
      - uses: astral-sh/setup-uv@v5
        if: ${{ hashFiles('uv.lock') != '' }}
      - name: Install dependencies
        run: |
          if [ -f uv.lock ]; then
            uv sync
          else
            python -m pip install --upgrade pip
            if [ -f requirements.txt ]; then
              python -m pip install -r requirements.txt
            fi
            if [ -f pyproject.toml ] && \\
              grep -Eq '^[[:space:]]*\\[(project|build-system)\\]' pyproject.toml; then
              python -m pip install -e .
            fi
            if ! python -c "import kensa" >/dev/null 2>&1; then
              python -m pip install kensa
            fi
          fi
      - name: Run Kensa eval
        run: |
          if [ -f uv.lock ]; then
            if uv run python -c "import kensa" >/dev/null 2>&1; then
              uv run kensa eval
            else
              uv run --with kensa kensa eval
            fi
          else
            kensa eval
          fi
"""

CONFTEST_TEMPLATE = '''"""Repository-specific Kensa harness connection."""

from __future__ import annotations

import pytest

# Generated by kensa init. Replace the placeholder with the real local boundary.


@pytest.fixture
def kensa_run():
    """Adapter from a Kensa case to the real local agent runtime in this repo."""

    def _run(case):
        raise NotImplementedError(
            "Connect this fixture to your agent using safe local, staging, or mocked dependencies."
        )

    return _run
'''

SMOKE_TEMPLATE = f'''"""Persistent Kensa smoke readiness eval."""

from __future__ import annotations

import pytest

from kensa.pytest import kensa_case

# Generated by kensa init. Kensa may refresh this smoke contract.


@pytest.mark.kensa(trials=1)
@pytest.mark.parametrize("case", [kensa_case(id="{SMOKE_CASE_ID}", input="hello")])
def test_kensa_smoke(case, kensa_run, kensa_trace):
    output = case.run(kensa_run)
    assert output is not None
    assert kensa_trace.llm_turns > 0, (
        "Expected kensa_run to record at least one LLM span. "
        "Wrap the real model/provider call with kensa.record_llm_call(...)."
    )
'''
