"""Static constants and text templates for Kensa."""

from __future__ import annotations

from pathlib import Path

DEFAULT_EVAL_PATHS = ("tests/evals",)
KENSA_DIR = Path(".kensa")
INSPECT_DIR = KENSA_DIR / "inspect"
SMOKE_CASE_ID = "kensa_smoke"
SMOKE_NODEID_FRAGMENT = "test_kensa_smoke.py::test_kensa_smoke"
TRACE_IMPORT_LATEST_SCHEMA_VERSION = "kensa.trace_import_latest.v1"
TRACE_IMPORTS_DIR = KENSA_DIR / "traces" / "imports"

ENDPOINT_ENV_KEY_FRAGMENTS = ("URL", "URI", "ENDPOINT", "HOST", "BASE")
LOCAL_ENDPOINT_HOSTS = {"localhost", "127.0.0.1", "::1", "0.0.0.0"}

SETUP_HANDOFF_PROMPT = (
    "Use the generated kensa-evals skill to continue the Kensa lifecycle for this repo: "
    "setup -> evidence -> inspect -> approval -> generate -> verify. Start with state detection. "
    "Read [tool.kensa] in pyproject.toml for the selected trace source. "
    "Detect credentials by name only; "
    "never read or print API keys or .env files."
)

# fmt: off
CLI_LOGO = (
    "┌────────────────────────────────────────────────────────┐\n"
    "│ ░██    ░██ ░███████  ░████████   ░███████   ░██████    │\n"
    "│ ░██   ░██ ░██    ░██ ░██    ░██ ░██              ░██   │\n"
    "│ ░███████  ░█████████ ░██    ░██  ░███████   ░███████   │\n"
    "│ ░██   ░██ ░██        ░██    ░██        ░██ ░██   ░██   │\n"
    "│ ░██    ░██ ░███████  ░██    ░██  ░███████   ░█████░██  │\n"
    "└────────────────────────────────────────────────────────┘"
)
# fmt: on

CLI_EPILOG = """\b
Examples:
  kensa init
  kensa doctor --json
  kensa import --from jsonl --source traces.jsonl
  kensa traces sample --json
  kensa eval --workers 1
  kensa eval -- --maxfail=1 -q

Pass extra pytest arguments after --.
"""

WORKFLOW_TEXT = """name: Kensa

on:
  pull_request:
  push:
    branches: [main]

jobs:
  kensa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        if: ${{ hashFiles('uv.lock') == '' }}
        with:
          python-version: "3.11"
      - uses: astral-sh/setup-uv@v5
        if: ${{ hashFiles('uv.lock') != '' }}
      - name: Install dependencies
        run: |
          if [ -f uv.lock ]; then
            uv sync
          else
            python -m pip install --upgrade pip
            if [ -f requirements.txt ]; then
              python -m pip install -r requirements.txt
            fi
            if [ -f pyproject.toml ] && \\
              grep -Eq '^[[:space:]]*\\[(project|build-system)\\]' pyproject.toml; then
              python -m pip install -e .
            fi
            if ! python -c "import kensa" >/dev/null 2>&1; then
              python -m pip install kensa
            fi
          fi
      - name: Run Kensa eval
        run: |
          if [ -f uv.lock ]; then
            if uv run python -c "import kensa" >/dev/null 2>&1; then
              uv run kensa eval
            else
              uv run --with kensa kensa eval
            fi
          else
            kensa eval
          fi
"""

CONFTEST_TEMPLATE = '''"""Repository-specific Kensa harness connection."""

from __future__ import annotations

import pytest

from kensa.pytest import ConversationResponse, KensaCase, KensaMessage

# Generated by kensa init. Replace the placeholder with the real local boundary.


class RepositoryAgent:
    """Case-aware adapter for the repository's real local agent runtime."""

    def __init__(self, case: KensaCase) -> None:
        self.case = case

    def respond(self, messages: tuple[KensaMessage, ...]) -> ConversationResponse:
        raise NotImplementedError(
            "Connect this agent to safe local, staging, or mocked dependencies."
        )


@pytest.fixture
def kensa_run(case: KensaCase) -> RepositoryAgent:
    """Create one case-aware agent instance for this trial."""

    return RepositoryAgent(case)
'''

SMOKE_TEMPLATE = f'''"""Persistent Kensa smoke readiness eval."""

from __future__ import annotations

import asyncio
import inspect

import pytest

from kensa.pytest import kensa_case

# Generated by kensa init. Kensa may refresh this smoke contract.


async def _resolve(awaitable):
    return await awaitable


@pytest.mark.kensa(trials=1)
@pytest.mark.parametrize("case", [kensa_case(id="{SMOKE_CASE_ID}", input="hello")])
def test_kensa_smoke(case, kensa_run):
    result = case.run(kensa_run)
    if inspect.isawaitable(result):
        result = asyncio.run(_resolve(result))
    assert result.output is not None
    assert result.trace.llm_turns > 0, (
        "Expected kensa_run to record at least one LLM span. "
        "Wrap the real model/provider call with kensa.record_llm_call(...)."
    )
'''
